### ISSUE TITLE
Create form submit action for "Get a detailled price report"

### ISSUE THREAD

**Issue by StudioSpindle** [semi-technologies/semi-website#305]
When the user successfully fills out the form, the "Schedule a call" goes to the contact page.

The option "Get a detailled price report" should... **T.B.D.**

**Comment by StudioSpindle** [comment]
@bobvanluijt what should the get detailled price report action do?

**Comment by bobvanluijt** [comment]
@StudioSpindle, it should show the table with detailed pricing information. So, this call costs x, that call costs y, etc as shown in the image below. We _don't_ want to show that, only the totals and allow people to unfold to get more details.

<img width="806" alt="screenshot 2019-03-06 at 15 42 56" src="https://user-images.githubusercontent.com/5509162/53889372-9c7ec780-4026-11e9-9c8c-990da5140ba6.png">

**Comment by StudioSpindle** [comment]
@bobvanluijt, So if you click on the link in the receipt the use-case view should expand? I think @rafaelcanalesduron designed this more like a function where a user can receive a detailled report in their inbox or as a PDF. 

Perhaps its better to remove that option from the receipt since if the link is in the receipt people read it in a different context. And we already have a large expansion panel where someone can request more information if needed.

So the last thing for me to do then is link the button "Schedule a call" to the contact page.

**Comment by rafaelcanalesduron** [comment]
@bobvanluijt @StudioSpindle the button should act as a CTA so that once potential customers get a price and if they want more information we give them something extra in exchange for contact information. This is interesting to feed a lead generation funnel for sales.

What that CTA should be was not defined yet. For now because we will still experiment with it, it might be enough with "schedule a call". If possible I would not make this a direct link to the contact page, but maybe an alternative one where we can link the contact info to the answers the potential lead gave.

Another option is to use a platform like Calendly to directly schedule calls and contact info.
https://calendly.com/pages/solutions/sales-and-marketing

**Comment by bobvanluijt** [comment]
<img width="820" alt="Screenshot 2019-03-11 at 09 09 33" src="https://user-images.githubusercontent.com/5509162/54129950-67cf8f00-43dd-11e9-974e-bb89cd53a327.png">

This interaction is exactly correct. However, it is now directly under the "use case selection". It would IMHO be better to have it at the bottom because all other selection options influence the price.
