### ISSUE TITLE
Add docs for weaviate-python-client

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/semi-website#406]
A [Python client](https://github.com/semi-technologies/weaviate-python-client) has been developed and needs documentation.
Documentation can be partly autogenerated from the comments in the python code, but should be enhanced with example uses.

Should we add the documentation as page on documentation section of Weaviate? @bobvanluijt

**Comment by bobvanluijt** [comment]
It depends how big it gets. Would an addition to the Weaviate docs with "client libraries" be enough?

**Comment by fefi42** [comment]
We have this issue https://github.com/semi-technologies/weaviate-python-client/issues/9 which creates a standardized form of code documentation. I think it is possible to autogenerate the documentation from there (have to look into that more). Then the only thing that we would need additionally is a quickstart guide with some code examples and a collection of all the links. This should fit easily on one page since using the the client only takes a few lines of code something like this:
```
import weaviate
client = weaviate.Client("http://localhost:8080")
client.create_schema("http://semi.technologies/example/schema.json")
client.self.create_thing({
      "name": "Thor"
}, "Heroes")
```
